version: "3.8"

services:
  redis-node-0:
    image: redis:latest
    container_name: node0
    volumes:
      - ./redis/cluster-0/redis.conf:/etc/usr/local/redis.conf
      - ./redis/cluster-0/data:/data
    network_mode: host
    command: redis-server /etc/usr/local/redis.conf

  redis-node-1:
    image: redis:latest
    container_name: node1
    volumes:
      - ./redis/cluster-1/redis.conf:/etc/usr/local/redis.conf
      - ./redis/cluster-1/data:/data
    network_mode: host
    command: redis-server /etc/usr/local/redis.conf

  redis-node-2:
    image: redis:latest
    container_name: node2
    volumes:
      - ./redis/cluster-2/redis.conf:/etc/usr/local/redis.conf
      - ./redis/cluster-2/data:/data
    network_mode: host
    command: redis-server /etc/usr/local/redis.conf

  redis-node-3:
    image: redis:latest
    container_name: node3
    volumes:
      - ./redis/cluster-3/redis.conf:/etc/usr/local/redis.conf
      - ./redis/cluster-3/data:/data
    network_mode: host
    command: redis-server /etc/usr/local/redis.conf

  redis-node-4:
    image: redis:latest
    container_name: node4
    volumes:
      - ./redis/cluster-4/redis.conf:/etc/usr/local/redis.conf
      - ./redis/cluster-4/data:/data
    network_mode: host
    command: redis-server /etc/usr/local/redis.conf

  redis-node-5:
    image: redis:latest
    container_name: node5
    volumes:
      - ./redis/cluster-5/redis.conf:/etc/usr/local/redis.conf
      - ./redis/cluster-5/data:/data
    network_mode: host
    command: redis-server /etc/usr/local/redis.conf
    entrypoint: ["sh", "-c", "sleep 10 && redis-cli --cluster create 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384 127.0.0.1:6385 --cluster-replicas 1 --cluster-yes -a Eranga123"]