version: "3.8"

services:

  redis-cluster-0:
    container_name: redis-cluster-0
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis-cluster-0/redis.conf:/etc/usr/local/redis.conf
      - ./redis/redis-cluster-0/data:/data
    ports:
      - "6390:6390"
    networks:
      redis-cluster:
    command: "redis-server /etc/usr/local/redis.conf"

  redis-cluster-1:
    container_name: redis-cluster-1
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis-cluster-1/redis.conf:/etc/usr/local/redis.conf
      - ./redis/redis-cluster-1/data:/data
    ports:
      - "6391:6391"
    command: "redis-server /etc/usr/local/redis.conf"
    depends_on:
      - redis-cluster-0
    networks:
      redis-cluster:

  redis-cluster-2:
    container_name: redis-cluster-2
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis-cluster-2/redis.conf:/etc/usr/local/redis.conf
      - ./redis/redis-cluster-2/data:/data
    ports:
      - "6392:6392"
    command: "redis-server /etc/usr/local/redis.conf"
    depends_on:
      - redis-cluster-1
    networks:
      redis-cluster:

  redis-cluster-3:
    container_name: redis-cluster-3
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis-cluster-3/redis.conf:/etc/usr/local/redis.conf
      - ./redis/redis-cluster-3/data:/data
    ports:
      - "6393:6393"
    command: "redis-server /etc/usr/local/redis.conf"
    depends_on:
      - redis-cluster-2
    networks:
      redis-cluster:

  redis-cluster-4:
    container_name: redis-cluster-4
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis-cluster-4/redis.conf:/etc/usr/local/redis.conf
      - ./redis/redis-cluster-4/data:/data
    ports:
      - "6394:6394"
    command: "redis-server /etc/usr/local/redis.conf"
    depends_on:
      - redis-cluster-3
    networks:
      redis-cluster:

  redis-cluster-5:
    container_name: redis-cluster-5
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis-cluster-5/redis.conf:/etc/usr/local/redis.conf
      - ./redis/redis-cluster-5/data:/data
    ports:
      - "6395:6395"
    command: "redis-server /etc/usr/local/redis.conf"
    depends_on:
      - redis-cluster-4
    networks:
      redis-cluster:

networks:
  redis-cluster:
    driver: bridge

